#!/usr/bin/perl
use 5.14.2;
use Net::SSH::Perl;
print "enter root password\n";
my $p = <STDIN>;
print "Enter nfs server IP:\n";
my $ip0 = <STDIN>;
print "Enter nfs server share location: \n";
my $share = <STDIN>;
print "Enter start host:\n";
my $ip1 = <STDIN>; 
print "Enter end host:\n";
my $ip2 = <STDIN>;
chomp $p;
chomp $share;
chomp $ip0;
chomp $ip1;
chomp $ip2;
my $login = "root";
my $passwd = $p;
chomp $passwd;
my $cmd = "mount -t nfs -o proto=tcp,port=2049 $ip0:$share /mnt";
while ($ip1 <= $ip2)
{
    my $ssh = Net::SSH::Perl->new("172.16.1.$ip1");  
    $ssh->login($login, $passwd);
    my ($stdout, $stderr,$exit) = $ssh->cmd($cmd);
    print "$ip1 works\n";
    $ip1++;
} 
